all:
    vars:
      ansible_connection: ssh
      ansible_user: mysmith
      ansible_become_method: dzdo
      ansible_become: true



zookeeper:
  hosts:
    
     mysmith-adm01

kafka_broker:
  hosts:
    mysmith-adm02
    mysmith-adm01

schema_registry:
  hosts:
    

kafka_rest:
  hosts:
    

ksql:
  hosts:
    


kafka_connect:
  hosts:
      

control_center:
  hosts:
        
        ## To configure Control Center to run as a custom user, uncomment below
        # vars:
        #   control_center_user: custom-user
        #   control_center_group: custom-group

        ## For kerberos sasl protocol, EACH host will need these two variables:
        # control_center_kerberos_keytab_path: <The path on ansible host to keytab file, eg. /tmp/keytabs/controlcenter-ip-172-31-37-15.us-east-2.compute.internal
        # control_center_kerberos_principal: The principal configured in kdc server ex: controlcenter/ip-172-31-37-15.us-east-2.compute.internal@REALM.EXAMPLE.COM>
