all:
    vars:
      #ansible_connection: ssh
      ansible_user: mysmith
      ansible_become: true
      #ansilbe_pass: Summer@022020
      #ansible_ssh_private_key_file: ~/.ssh/mysmith-adm01.pem
      #ansilbe_ssh_pass: <ssh_pass>
      #become_method: dzdo

zookeeper:

  hosts:
    mysmith-adm01

kafka_broker:

  hosts:
    mysmith-adm01

schema_registry:

  hosts:
    mysmith-adm01

kafka_rest:

  hosts:
    mysmith-adm01

ksql:

  hosts:
    mysmith-adm01

kafka_connect:

  hosts:
      mysmith-adm01

control_center:

  hosts:
        mysmith-adm01
