 #all:
  #vars:
  #  ansible_connection: ssh
  #  ansible_user: mysmith
#    ansible_become: true
#    ansible_password: Summer@022020
    #ansible_ssh_private_key_file: /tmp/certs/ssh_priv.pem
localhost:
  127.0.0.1:
  
zookeeper:
  hosts:
    127.0.0.1:

kafka_broker:
  hosts:
    127.0.0.1:


schema_registry:
  hosts:
    127.0.0.1:

kafka_rest:
  hosts:
    127.0.0.1:

ksql:
  hosts:
    127.0.0.1:

kafka_connect:
  hosts:
    127.0.0.1:

control_center:

  hosts:
    127.0.0.1:
