all:
    vars:
      ansible_connection: ssh
      ansible_user: mysmith
      ansible_become_method: dzdo
      
      ansible_become: true
      #localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
      #ansible_ssh_private_key_file: ~/.ssh/ssh_rsa


zookeeper:

  hosts:
    mysmith-adm01


kafka_broker:

  hosts:
    mysmith-adm01

schema_registry:

  hosts:
    mysmith-adm01

kafka_rest:

  hosts:
    mysmith-adm01

ksql:

  hosts:
    mysmith-adm01

kafka_connect:

  hosts:
      mysmith-adm01

control_center:

  hosts:
        mysmith-adm01
